import ClickMe from '@/components/buttom'
import PostWithLike from '@/components/cards'
import LargeWithAppLinksAndSocial from '@/components/footer'
import WithSubnavigation from '@/components/navbar'
import WithSpeechBubbles from '@/components/testimonials'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WithSubnavigation></WithSubnavigation>
        <WithSpeechBubbles></WithSpeechBubbles>
        <ClickMe></ClickMe>
        <PostWithLike></PostWithLike>
        <LargeWithAppLinksAndSocial></LargeWithAppLinksAndSocial>
      </main>
    </>
  )
}
